#!/bin/bash
tmux has-session -t duane
if [ $? != 0 ]
then
    tmx duane
fi

tmux set pane-active-border-style fg=red
tmux set pane-border-style fg=blue
tmux split-window -h -t duane:0
tmux rename-window -t duane:0 "term"
tmux new-window -n "emacs" -t duane /usr/bin/emacs -nw
tmux new-window -n "ipython" -t duane /usr/bin/ipython3
tmux split-window -v -t duane:0.1 -l80%
tmux split-window -v -t duane:0.1 -l70%
tmux send-keys -t duane:0.1 "ping payload." C-m
tmux send-keys -t duane:0.2 "rostopic echo /Control/status | grep \"\(feedback\|status\|substatus\|operating_mode\|lights\):\"" C-m
